### ISSUE TITLE
Could not find a declaration file for module 'console-watcher'.

### ISSUE THREAD

**Issue by johnexzy** [francosion042/console-watcher#1]
When installing the package on a typescript project, i encountered this 

``Could not find a declaration file for module 'console-watcher'``

Despite my attempt to resolve the issue by running the command

``npm i --save-dev @types/console-watcher``

I was unable to locate the required declaration file.

**Comment by francosion042** [comment]
Thanks for the feedback, this issue has been resolved [v0.0.2](https://www.npmjs.com/package/console-watcher/v/0.0.2)
